### ISSUE TITLE
What are the build instructions?

### ISSUE THREAD

**Issue by noah-** [IAmTrial/SlashDiablo-HD-DLL#41]
Hi, I attempted to build the source on linux with the following:
`i686-w64-mingw32-g++-win32 DLLmain.cpp -std=c++1z -l Version -Wall`

resulting in errors such as:
`D2Patches.h:116:6: error: no matching function for call to ‘D2Offset::D2Offset(D2TEMPLATE_DLL_FILES, <brace-enclosed initializer list>)`

I wanted to check if I'm following the right steps before starting triage on the build errors.

**Comment by IAmTrial** [comment]
Hi noah, the project is now archived. Please check out this project's successor, [SGD2FreeRes](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution).
