### ISSUE TITLE
1024x768 border glitch

### ISSUE THREAD

**Issue by tytannial** [IAmTrial/SlashDiablo-HD-DLL#43]
In gdi mode, some bottom graphic is draw at the top. So it is why height limit is 700?
The window height over than 800 also crashes the game. But width, I set it to 2560x700 it works fine.

**Comment by IAmTrial** [comment]
As the height increases, the stability of the game decreases. So far, I have not been able to solve this issue. I know that Glide mode does not have this issue.

**Comment by tytannial** [comment]
But it is fantastic, playing with 960x720 and 1280x720 is great. 👍
