### ISSUE TITLE
nGlide 2.1.0 The effect of 3DFX is perfect~

### ISSUE THREAD

**Issue by MxCen** [IAmTrial/SlashDiablo-HD-DLL#44]
I have extracted the DLL and dropped it into the game root directory . 

Can I optimize it?

I think maybe he can solve the BUG beyond 700resolution.

[nGlide 2.1.0.zip](https://github.com/IAmTrial/SlashDiablo-Tools/files/5048829/nGlide.2.1.0.zip)

**Comment by MxCen** [comment]
width     0x169DA4
height    0x169F04

**Comment by IAmTrial** [comment]
Hi MxCen, the project is now archived. Please check out this project's successor, [SGD2FreeRes](https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution).
